export enum TaskStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum TaskType {
  COLLECT_SEMANTICS = 'COLLECT_SEMANTICS',
  CLUSTERING = 'CLUSTERING',
  GENERATE_CONTENT_PLAN = 'GENERATE_CONTENT_PLAN',
  GENERATE_ARTICLE = 'GENERATE_ARTICLE',
  GENERATE_IMAGE = 'GENERATE_IMAGE',
  PUBLISH_CONTENT = 'PUBLISH_CONTENT',
  ANALYZE_SEO = 'ANALYZE_SEO'
}

export enum ProjectStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED'
}

export enum ContentStatus {
  DRAFT = 'DRAFT',
  GENERATING = 'GENERATING',
  REVIEW_NEEDED = 'REVIEW_NEEDED',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED'
}
